version: "3.4"

networks:
    localdev:
        name: localdev
services:
    integrationtests:
        build: 
            context: ./
            dockerfile: ./DevicesApi.IntegrationTests/Dockerfile.tests.integration
        depends_on:
            - db
            - api
        links:
             - api
        networks:
            - localdev
            
    unittesting:
        build: 
            context: ./
            dockerfile: ./DevicesApi.UnitTests/Dockerfile.tests.unit
            
    api:
        build: DevicesApi/
        restart: always
        ports:
            - "8000:80"
        depends_on:
            - db
        networks:
            - localdev
                
    db:
        image: "microsoft/mssql-server-linux"
        container_name: db
        environment: 
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=Pedro*12345
            - MSSQL_TCP_PORT=1433
        ports:
            - "1400:1433"
        networks:
            - localdev